version: '3.2'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db-data:/var/lib/mysql
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress-data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    volumes:
      - wordpress-data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    expose:
      - "9000"

volumes:
  wordpress-data:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /home/${USER}/data/wordpress
  db-data:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /home/${USER}/data/maria_db

networks:
  inception:
    driver: bridge
