# Configuration Nginx

# Définir le nombre de worker processes à utiliser
worker_processes 1;

# Configuration des events
events {
  worker_connections 1024;
}

# Configuration du serveur
http {
  # Définir le mime-type par défaut
  include /etc/nginx/mime.types;

  # Définir le format de fichier par défaut
  default_type application/octet-stream;

  # Configuration du serveur
  server {
    # Écouter sur le port 443
    listen 443 ssl;
    server_name tdelauna.42.fr;

    ssl_certificate /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/key.pem;

    ssl_protocols TLSv1.3;

    # Définir le répertoire racine des fichiers statiques
    root /var/www;

    # Définir le fichier d'index par défaut
    index index.php;

    # Configuration des requêtes
    location / {
        try_files $uri /index.php?$args;
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache';
        if_modified_since off;
        expires off;
        etag off;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
  }
}
