# Configuration Nginx

# Définir le nombre de worker processes à utiliser
worker_processes 1;

# Configuration des events
events {
  worker_connections 1024;
}

# Configuration du serveur
http {
  # Définir le mime-type par défaut
  include /etc/nginx/mime.types;

  # Définir le format de fichier par défaut
  default_type application/octet-stream;

  # Configuration du serveur
  server {
    # Écouter sur le port 443
    listen 443 ssl;
    server_name tdelauna.42.fr;

    ssl_certificate /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/key.pem;

    ssl_protocols TLSv1.3;

    # Définir le répertoire racine des fichiers statiques
    root /usr/share/nginx/html;

    # Définir le fichier d'index par défaut
    index index.html;

    # Configuration des requêtes
    location / {
      # Autoriser les requêtes entrantes
      allow all;

      # Afficher le fichier index.html pour toutes les requêtes
      try_files $uri $uri/ /index.html;
    }
  }
}
