# server
# {
# 	listen 443;
# 	listen [::]443;

# 	# server_name tdelauna.42.fr
# 	index index.html;
# 	root	/var/www/html
# 	location{
# 		try_files $uri $uri/ = 404;
# 	}
# }

server {

	listen 443 ;
	# listen [::]80;
	server_name tdelauna.42.fr;

	# ssl_protocols TLSv1.2 TLSv1.3;

	# ssl_certificate_key /etc/ssl/private/nginx.key;
	# ssl_certificate /etc/ssl/certs/nginx.crt;
	# Les urls commençant par / (toutes les urls)
	location / {
		root /home/dev/www/;
		index index.html;
		try_files $uri $uri/ $uri.html =404;
	}

	# Les urls contennant /. (dotfiles)
	location ~ /\. {
		deny all;
		access_log off;
		log_not_found off;
	}


	# On va placer les logs dans un dossier accessible
	error_log /home/dev/logs/error.log;
	access_log /home/dev/logs/acess.log;

	# Les pages d'erreurs
	error_page 404 500 501 /error.html;

}

server {
	# On redirige les www. vers la version sans www
	listen 443;
	server_name www.tdelauna.42.fr;
	return 301 http://tdelauna.42.fr$request_uri;
}


